version: "3"
services: 
   seleniumhub:
    image: selenium/hub:3.14.0-curium
    ports:
       - 4444:4444
    expose:
       - "22"
    container_name: hub
    networks:
       - myseleniumnet

   SamsungJ3:
     image: appium/appium
     privileged: true
     volumes:
       - /dev/bus/usb:/dev/bus/usb
       - ~/.android:/root/.android
     environment:
       - CONNECT_TO_GRID=true
     networks:
        - myseleniumnet

   Tablet:
     image: appium/appium
     privileged: true
     volumes:
       - /dev/bus/usb:/dev/bus/usb
       - /home/jenkins/android:/root/.android
     environment:
       - CONNECT_TO_GRID=true
     networks:
        - myseleniumnet
    
networks:
   myseleniumnet:
      driver: bridge

